// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agent} from '../models';
import {context} from '../models';

export function GetAgentSetupState():Promise<agent.SetupState>;

export function GetEnabledAgents():Promise<Array<string>>;

export function IsAgentEnabled(arg1:string):Promise<boolean>;

export function ListAgents():Promise<Array<agent.Agent>>;

export function SetEnabledAgents(arg1:Array<string>):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
