// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAgentSetupState() {
  return window['go']['app']['AgentApp']['GetAgentSetupState']();
}

export function GetEnabledAgents() {
  return window['go']['app']['AgentApp']['GetEnabledAgents']();
}

export function IsAgentEnabled(arg1) {
  return window['go']['app']['AgentApp']['IsAgentEnabled'](arg1);
}

export function ListAgents() {
  return window['go']['app']['AgentApp']['ListAgents']();
}

export function SetEnabledAgents(arg1) {
  return window['go']['app']['AgentApp']['SetEnabledAgents'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['AgentApp']['Startup'](arg1);
}
