// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoUpdate() {
  return window['go']['app']['AppPreferencesApp']['GetAutoUpdate']();
}

export function GetCloseBehavior() {
  return window['go']['app']['AppPreferencesApp']['GetCloseBehavior']();
}

export function HandleBeforeClose(arg1) {
  return window['go']['app']['AppPreferencesApp']['HandleBeforeClose'](arg1);
}

export function HideToTray() {
  return window['go']['app']['AppPreferencesApp']['HideToTray']();
}

export function RequestExit() {
  return window['go']['app']['AppPreferencesApp']['RequestExit']();
}

export function SetAutoUpdateEnabled(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateEnabled'](arg1);
}

export function SetAutoUpdateGithubRepo(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateGithubRepo'](arg1);
}

export function SetAutoUpdateGitlabHost(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateGitlabHost'](arg1);
}

export function SetAutoUpdateGitlabProject(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateGitlabProject'](arg1);
}

export function SetAutoUpdateInterval(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateInterval'](arg1);
}

export function SetAutoUpdateSkipVersion(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateSkipVersion'](arg1);
}

export function SetAutoUpdateSource(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetAutoUpdateSource'](arg1);
}

export function SetCloseBehavior(arg1) {
  return window['go']['app']['AppPreferencesApp']['SetCloseBehavior'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['AppPreferencesApp']['Startup'](arg1);
}
