// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {preferences} from '../models';
import {context} from '../models';

export function GetAutoUpdate():Promise<preferences.AutoUpdate>;

export function GetCloseBehavior():Promise<string>;

export function HandleBeforeClose(arg1:context.Context):Promise<boolean>;

export function HideToTray():Promise<void>;

export function RequestExit():Promise<void>;

export function SetAutoUpdateEnabled(arg1:boolean):Promise<void>;

export function SetAutoUpdateGithubRepo(arg1:string):Promise<void>;

export function SetAutoUpdateGitlabHost(arg1:string):Promise<void>;

export function SetAutoUpdateGitlabProject(arg1:string):Promise<void>;

export function SetAutoUpdateInterval(arg1:number):Promise<void>;

export function SetAutoUpdateSkipVersion(arg1:string):Promise<void>;

export function SetAutoUpdateSource(arg1:string):Promise<void>;

export function SetCloseBehavior(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
