// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListHooks(arg1, arg2) {
  return window['go']['app']['HooksApp']['ListHooks'](arg1, arg2);
}
