// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {marketplace} from '../models';
import {app} from '../models';

export function Add(arg1:string):Promise<marketplace.Marketplace>;

export function List():Promise<Array<marketplace.Marketplace>>;

export function Refresh():Promise<app.RefreshResult>;

export function Remove(arg1:string):Promise<void>;
