// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['app']['MarketplaceApp']['Add'](arg1);
}

export function List() {
  return window['go']['app']['MarketplaceApp']['List']();
}

export function Refresh() {
  return window['go']['app']['MarketplaceApp']['Refresh']();
}

export function Remove(arg1) {
  return window['go']['app']['MarketplaceApp']['Remove'](arg1);
}
