// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchAll() {
  return window['go']['app']['PluginApp']['FetchAll']();
}

export function Install(arg1, arg2) {
  return window['go']['app']['PluginApp']['Install'](arg1, arg2);
}

export function ListInstalled(arg1) {
  return window['go']['app']['PluginApp']['ListInstalled'](arg1);
}

export function SetContext(arg1) {
  return window['go']['app']['PluginApp']['SetContext'](arg1);
}

export function Uninstall(arg1, arg2) {
  return window['go']['app']['PluginApp']['Uninstall'](arg1, arg2);
}

export function UpdateAgentMarketplace(arg1) {
  return window['go']['app']['PluginApp']['UpdateAgentMarketplace'](arg1);
}

export function UpdateAgentMarketplaces() {
  return window['go']['app']['PluginApp']['UpdateAgentMarketplaces']();
}

export function UpdatePlugin(arg1, arg2) {
  return window['go']['app']['PluginApp']['UpdatePlugin'](arg1, arg2);
}
