// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plugin} from '../models';
import {context} from '../models';

export function FetchAll():Promise<plugin.FetchAllResult>;

export function Install(arg1:string,arg2:Array<plugin.MarketplacePlugin>):Promise<void>;

export function ListInstalled(arg1:string):Promise<Array<plugin.InstalledPlugin>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Uninstall(arg1:string,arg2:string):Promise<void>;

export function UpdateAgentMarketplace(arg1:string):Promise<plugin.AgentUpdateOutcome>;

export function UpdateAgentMarketplaces():Promise<plugin.UpdateAgentMarketplacesResult>;

export function UpdatePlugin(arg1:string,arg2:string):Promise<void>;
