// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sessionhistory} from '../models';

export function ListEvents(arg1:string,arg2:string,arg3:number,arg4:number):Promise<sessionhistory.EventPage>;

export function ListSessions(arg1:string):Promise<sessionhistory.Listing>;

export function SessionMeta(arg1:string,arg2:string):Promise<sessionhistory.SessionMeta>;
