// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['app']['SystemApp']['GetAppVersion']();
}

export function OpenPath(arg1) {
  return window['go']['app']['SystemApp']['OpenPath'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['SystemApp']['Startup'](arg1);
}
