// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoUpdateAvailable() {
  return window['go']['app']['UpdaterApp']['AutoUpdateAvailable']();
}

export function BuildKind() {
  return window['go']['app']['UpdaterApp']['BuildKind']();
}

export function CheckNow() {
  return window['go']['app']['UpdaterApp']['CheckNow']();
}

export function GetState() {
  return window['go']['app']['UpdaterApp']['GetState']();
}

export function HandleTrayOpen() {
  return window['go']['app']['UpdaterApp']['HandleTrayOpen']();
}

export function InProgress() {
  return window['go']['app']['UpdaterApp']['InProgress']();
}

export function InstallAvailable() {
  return window['go']['app']['UpdaterApp']['InstallAvailable']();
}

export function ManualRequired() {
  return window['go']['app']['UpdaterApp']['ManualRequired']();
}

export function PeekBothSources() {
  return window['go']['app']['UpdaterApp']['PeekBothSources']();
}

export function SkipVersion(arg1) {
  return window['go']['app']['UpdaterApp']['SkipVersion'](arg1);
}

export function Startup(arg1) {
  return window['go']['app']['UpdaterApp']['Startup'](arg1);
}

export function Unskip() {
  return window['go']['app']['UpdaterApp']['Unskip']();
}
