// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {context} from '../models';

export function CheckNow():Promise<void>;

export function GetState():Promise<updater.State>;

export function HandleTrayOpen():Promise<void>;

export function InProgress():Promise<boolean>;

export function InstallAvailable():Promise<void>;

export function ManualRequired():Promise<boolean>;

export function PeekBothSources():Promise<updater.PeekResult>;

export function SkipVersion(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function Unskip():Promise<void>;
